# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fxtec/pro1/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    bluetooth \
    modem \
    abl \
    dsp \
    cmnlib \
    cmnlib64 \
    devcfg \
    hyp \
    keymaster \
    mdtp \
    mdtpsecapp \
    pmic \
    rpm \
    tz \
    xbl
